name: Run performance tests and archive its result

on:
  push:
    branches: [ dev, staging, master ]

jobs:
  docker-build-push:
    runs-on: ubuntu-18.04
    steps:
    - name: Set image tag variable to 'dev'
      if: endsWith(github.ref, '/dev')
      run: echo "::set-env name=IMAGE_TAG::dev"
    - name: Set image tag variable to 'staging'
      if: endsWith(github.ref, '/staging')
      run: echo "::set-env name=IMAGE_TAG::staging"
    - name: Set image tag variable to 'latest'
      if: endsWith(github.ref, '/master')
      run: echo "::set-env name=IMAGE_TAG::latest"
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run performance tests
      run: ./mvnw verify --no-transfer-progress
    - name: Get current date for a git tag snapshot
      id: date
      run: echo "::set-output name=date::release-$(date +'%Y-%m-%d')"
    - uses: actions/upload-artifact@v2
      with:
        name: perf-tests-results.csv
        path: target/zerocode-junit-granular-report.csv